#!/bin/bash
#
# Resolve locations of object given identifier
#

source `dirname $0`/lib/d1_libbash.sh

if [ -z $BASEURL ]; then
  BASEURL=$CNBASE
fi

get_system_metadata $1
cat $TEMPOUTPUT

cleanup_temp_files