#!/bin/bash
#
# List objects from node, defaulting to the base CN
#

source `dirname $0`/lib/d1_libbash.sh

if [ -z $BASEURL ]; then
  BASEURL=$CNBASE
fi

get_object_list
printf "$OBJECTLIST\n"

cleanup_temp_files
