#!/bin/bash
#
# Resolve locations of object given identifier
#

source `dirname $0`/lib/d1_libbash.sh

if [ -z $BASEURL ]; then
  BASEURL=$CNBASE
fi

resolve_object_nodes $1
for ID in ${NODEIDS}; do
  echo $ID;
done

cleanup_temp_files
