#!/bin/bash
#
# Show the DataONE subject contained in a certificate .pem file.
#
# You will need python source for d1_common_python and d1_instance_generator to 
# run this script. These can be retrieved from svn at:
#   https://repository.dataone.org/software/cicore/trunk
#
# D.V.
#

VERSION="Version 0.0.1"

#Base path to folder containing the python stuff
WD="$HOME/Workspaces/DataONE_trunk/"
export PYTHONPATH=".:$WD/d1_common_python/src:$WD/d1_instance_generator/src"

#Script that given a cert, prints subject to stdout
MYSUBJECT="$WD/d1_instance_generator/src/my_subject.py"

#Location of XMLStarlet command
XML="/usr/local/bin/xml"
TMP="/tmp"

verbose=""
certificate=""

usage()
{
cat << EOF

usage: $(basename $0) CERTIFICATE

Show the DataONE subject info in a certificate.

OPTIONS:

  -h  Show this message
  -v  Be a bit more verbose
  -V  Show version (${VERSION})

EOF
}

show_version()
{
  echo ${VERSION}
}


while getopts "hvV" OPTION
do
    case $OPTION in
      h) usage; exit 3;;
      v) verbose=1;;
      V) show_version; exit 3;;
      \?) usage; exit 3;;
    esac
done

shift $(($OPTIND - 1))
certificate=$1

if [[ -z ${certificate} ]]; then
  echo "Certificate is required"
  exit 2
fi

my_subject=$(python ${MYSUBJECT} -l 40 ${certificate})
if [[ $? -ne 0 ]]; then
  if [[ -n ${dryrun} ]]; then
    echo "WARNING : certificate ${certificate} has expired."
  else
    echo "ERROR   : certificate ${certificate} has expired."
    exit 2
  fi
fi
if [[ -n ${verbose} ]]; then
  echo "SUBJECT : $my_subject"
else
  echo "$my_subject"
fi
